DELETE FROM telefone;
DELETE FROM classificacao;
DELETE FROM itens_pedido;
DELETE FROM produto;
DELETE FROM pedido;
DELETE FROM endereco;
DELETE FROM empresa;
DELETE FROM cliente;
DELETE FROM categoria;

ALTER TABLE categoria ALTER COLUMN id RESTART WITH 1;
ALTER TABLE produto ALTER COLUMN id RESTART WITH 1;
ALTER TABLE pedido ALTER COLUMN id RESTART WITH 1;
ALTER TABLE endereco ALTER COLUMN id RESTART WITH 1;
ALTER TABLE empresa ALTER COLUMN id RESTART WITH 1;
ALTER TABLE cliente ALTER COLUMN id RESTART WITH 1;

